name: Build iOS
on: [push]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode_16.2.app

      - name: Install .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Install MAUI workloads
        run: dotnet workload install maui-ios maui-android maui-maccatalyst

      - name: Restore
        run: dotnet restore ToDoApp/ToDoApp.csproj

      - name: Build IPA
        run: dotnet publish ToDoApp/ToDoApp.csproj -f net9.0-ios -c Release -p:RuntimeIdentifier=ios-arm64 -p:CodesignKey="" -p:CodesignProvision=""

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: app-ipa
          path: '**/*.ipa'
