name: Build iOS
on: [push]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Install MAUI workload
        run: dotnet workload install maui-ios

      - name: Build IPA
        run: dotnet publish ToDoApp/ToDoApp.csproj -f net10.0-ios -c Release -p:RuntimeIdentifier=ios-arm64 -p:CodesignKey="" -p:CodesignProvision=""

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: app-ipa
          path: '**/*.ipa'
